apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-microshift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      initContainers:
      - name: init-www
        image: quay.io/redhattraining/hello-world-nginx:v1.0
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c', 'echo "Hello from MicroShift LVM Storage" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: quay.io/redhattraining/hello-world-nginx:v1.0
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        ports:
        - name: web-8080
          containerPort: 8080
        volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: hello-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
    - name: http-port      # This name is the anchor
      protocol: TCP
      port: 80             # The 'outside' port
      targetPort: 8080     # The 'inside' container port
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-route
spec:
  host: hello-route-default.apps.example.com
  to:
    kind: Service
    name: hello-service
  port:
    targetPort: http-port  # Links directly to the Service port name
